# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TestMap
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/testmap" # the subpath of your site, e.g. /blog
url: "http://tips.mikegardner.me.uk" # the base hostname & protocol for your site

port: 			  4113

# Build settings
markdown: kramdown

# Prose.io editor settings
prose:
  rooturl: 'partnerships'
  metadata:
    partnerships:
      - name: "layout"
        field:
          element: "hidden"
          value: "modal"
      - name: "title"
        field:
          element: "text"
          label: "Partnership"
          help: "Name of Partnership"
      - name: "id"
        field:
          element: "number"
          label: "ID"
          help: "Internal identifier; incrementing number - check which is next at <insert url>"
      - name: "area"
        field:
          element: "select"
          label: "Area"
          help: "Scope of area covered NB. add definition re regional?"
          options:
           - name: "Regional"
             value: "Regional"
           - name: "Subregional"
             value: "Subregional"
           - name: "Local"
             value: "Local"
      - name: "chaired"
        field:
          element: "select"
          label: "Chaired by"
          help: "Type of organisation that chairs the partnership"
          options:
           - name: "Crown Prosecution Service"
             value: "Crown Prosecution Service"
           - name: "Government"
             value: "Government"
           - name: "Health"
             value: "Health"
           - name: "Independent"
             value: "Independent"
           - name: "Local Authority (district)"
             value: "Local Authority (district)"
           - name: "Local Authority (top tier)"
             value: "Local Authority (top tier)"
           - name: "Local Government Association"
             value: "Local Government Association"
           - name: "Non Government Oganisation"
             value: "Non Government Oganisation"
           - name: "Police & Crime Comissioner"
             value: "Police & Crime Comissioner"
           - name: "Police"
             value: "Police"
           - name: "Police / NGO"
             value: "Police / NGO"
           - name: "Rotates"
             value: "Rotates"
           - name: "To be determined"
             value: "To be determined"
      - name: "coordinated"
        field:
          element: "select"
          label: "Coordinated by"
          help: "Type of organisation that coordinates the partnership"
          options:
           - name: "Crown Prosecution Service"
             value: "Crown Prosecution Service"
           - name: "Government"
             value: "Government"
           - name: "Health"
             value: "Health"
           - name: "Independent"
             value: "Independent"
           - name: "Local Authority (district)"
             value: "Local Authority (district)"
           - name: "Local Authority (top tier)"
             value: "Local Authority (top tier)"
           - name: "Local Government Association"
             value: "Local Government Association"
           - name: "Non Government Oganisation"
             value: "Non Government Oganisation"
           - name: "Police & Crime Comissioner"
             value: "Police & Crime Comissioner"
           - name: "Police"
             value: "Police"
           - name: "Police / NGO"
             value: "Police / NGO"
           - name: "Rotates"
             value: "Rotates"
           - name: "To be determined"
             value: "To be determined"
      - name: "activities"
        field:
          element: "multiselect"
          label: "Activities"
          help: "If activities that not in this list then tick 'Other' and fill in next field"
          options:
           - name: "Co-ordinating referrals"
             value: "Co-ordinating referrals"
           - name: "Community awareness-raising"
             value: "Community awareness-raising"
           - name: "Frontline staff training"
             value: "Frontline staff training"
           - name: "Intelligence sharing"
             value: "Intelligence sharing"
           - name: "Joint commissioning of services"
             value: "Joint commissioning of services"
           - name: "Monitoring and analysis of progress"
             value: "Monitoring and analysis of progress"
           - name: "Other"
             value: "Other"
           - name: "Planning for joint enforcement"
             value: "Planning for joint enforcement"
           - name: "Supply chains analysis"
             value: "Supply chains analysis"
           - name: "Survivor support"
             value: "Survivor support"
