# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TestMap
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

port: 			  4001

# Build settings
markdown: kramdown

# Prose.io editor settings
prose:
  rooturl: 'partnerships'
  metadata:
    partnerships:
      - name: "layout"
        field:
          element: "hidden"
          value: "modal"
      - name: "title"
        field:
          element: "text"
          help: "Name of Partnership"
      - name: "id"
        field:
          element: "number"
          help: "Internal identifier; incrementing number - check which is next at <insert url>"
      - name: "area"
        field:
          element: "select"
          help: "Scope of area covered <add definition re regional?>"
          options:
           - name: "Regional"
             value: "Regional"
           - name: "Subregional"
             value: "Subregional"
           - name: "Local"
             value: "Local"
